[build]
build_dir = "./_site"
templates_dir = "./templates"
static_dir = "./static"

[overview]
name = "Matt Baughman"
titles = ["PhD Candidate", "Computer Scientist"]
headshot = "images/headshot.jpg"
contacts = [
    { name = "email", link = "mailto:mbaughman123@gmail.com" },
    { name = "github", link = "https://github.com/mattebaughman" },
    { name = "linkedin", link = "https://www.linkedin.com/in/mattebaughman/" },
    { name = "scholar", link = "https://scholar.google.com/citations?user=oehomH0AAAAJ" },
]
analytics = ""
source = "https://github.com/mattebaughman/mattebaughman.github.io/"
text = """
Hi there!
I recently completed my Ph.D. in Computer Science with <a href="https://labs.globus.org" target="_blank">Globus Labs</a> at the <a href="https://cs.uchicago.edu/" target="_blank">University of Chicago</a>,
where I was co-advised by <a href="https://cs.uchicago.edu/people/ian-foster/" target="_blank">Ian Foster</a> and <a href="https://kylechard.com/" target="_blank">Kyle Chard</a>.
My research spans high-performance computing, distributed systems, and cost-aware computing.
I completed my Bachelors in Computer Science and Philosphy at <a href="https://minerva.edu/" target="_blank">Minerva University</a> and have experience at Argonne National Lab, Opinary, and Google.
"""

[research]
sections = [
    { name = "Distributed Systems", text = "We are designing new programming paradigms which decouple system configuration and control from application design to enable multi-system workflows spanning HPC, the cloud, and the edge." },
    { name = "Federated Learning", text = "We are exploring new techniques for improving distributed deep learning using self-adaptive system design and online feedback to enable complex, hierarchical federated learning across diverse ecosystems of hardware." },
    { name = "Cost-aware Computing", text = "We are building scalable frameworks for highly distributed science workflows spanning dozens of computing sites and scaling to tens of thousands of compute nodes using novel cost-aware task placement algorithms and federated function-as-a-service infrastructure."}
]

[projects]
github = "https://github.com/mattebaughman/"
links = [
    { name = "", link = "", description = "" },
]

[publications]
bibtex = "publications/baughman.bib"
publications_dir = "./config/publications"

[presentations]
presentations_dir = "./config/presentations"

[theses]
theses_dir = "./config/theses"
